config/routes.rb
DistroaulasRails3::Application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users do
    get 'reset_pass'
    put 'update_pass'
  end

  match '/administration' => 'administration#index', :as => 'administration_index'
  scope '/administration' do
    get '/statics' => 'administration#statics', :as => 'statics'
  end

  scope '/importer' do
    get '/' => 'importer#index', :as => 'importer_index'
    get '/space_types' => 'importer#space_types', :as => 'import_space_types'
    get '/spaces' => 'importer#spaces', :as => 'import_spaces'
    get '/plans' => 'importer#plans', :as => 'import_plans'
    get '/careers' => 'importer#careers', :as => 'import_careers'
    get '/matters' => 'importer#matters', :as => 'import_matters'

    get 'career_template' => 'importer#career_template', :as => 'career_template'
    get 'matter_template' => 'importer#matter_template', :as => 'matter_template'
    get 'space_template' => 'importer#space_template', :as => 'space_template'
    get 'space_type_template' => 'importer#space_type_template', :as => 'space_type_template'
    get 'plan_template' => 'importer#plan_template', :as => 'plan_template'

    get '/importer/result' => 'importer#result', :as => 'import_result'

    post '/space_types' => 'importer#upload_space_types', :as => 'importer_upload_space_types'
    post '/spaces' => 'importer#upload_spaces', :as => 'importer_upload_spaces'
    post '/plans' => 'importer#upload_plans', :as => 'importer_upload_plans'
    post '/careers' => 'importer#upload_careers', :as => 'importer_upload_careers'
    post '/matters' => 'importer#upload_matters', :as => 'importer_upload_matters'
  end

  scope '/equipment' do
    post '/search_events' => 'equipment#search_events', :as => 'search_events_equipment'
    get '/calendar' => 'equipment#calendar', :as => 'calendar_equipments'
    post '/calendar' => 'equipment#calendar', :as => 'calendar_equipments'
  end
  resources :equipment, :only => [:index, :new, :create, :update, :destroy, :edit] do
    member do
      get :assign_event
      post :assign_event
      post :create_events
      get :equipment_events
      delete :remove_event
      get :new_event
      post :create_single_event
    end
  end

  resources :calendars

  resources :events do
    collection do
      post 'calendar_preview'
      post 'generate_calendar'
      get 'generate_calendar'
    end
  end
  match 'ajax_get_responsibles_list' => 'events#get_responsibles_list'
  match 'ajax_search_events' => 'events#search'
  match 'ajax_careers_by_plan/:id' => 'careers#ajax_careers_by_plan'
  match 'new_event' => 'application#new_event', :as => 'new_event_from_free_space'
  match 'events/tip_summary/:id' => 'events#tip_summary'
  match '/ajax_event_info' => 'equipment#event_info'

  resources :space_types, :only => [:index, :new, :create, :update, :destroy, :edit]

  resources :plans

  resources :matters
  match 'ajax_get_matters_by_career/:id' => 'matters#ajax_get_matters_by_career'

  resources :spaces
  match 'ajax_free_spaces' => 'spaces#ajax_free_spaces'

  resources :careers

  root :to => "application#index"

  match '/statics/index' => "statics#index"
  match '/statics/:category/:doc' => 'statics#view_doc'

end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  before_filter :authenticate_user!, :check_role

  def index
  end

  def statics
    @events_count = Event.count
    @matters_count = Matter.count
    @careers_count = Career.count
    @plans_count = Plan.count
    @spaces_count = Space.count
    @calendars_count = Calendar.count
    @equipment_count = Equipment.count
    @expired_events = Event.expired_events_count
    @assigned_matters = Matter.with_events_count
    @free_events = Event.free_events_count
    @assigned_spaces = Space.with_events_count
    @unassigned_spaces = Space.with_no_events_count
    @unassigned_matters = Matter.with_no_events_count
    @user_count = User.count
    @admin_count = User.admin_count
    @op_count = User.op_count
    @normal_users_count = User.user_count

  end

  private
  def check_role
    if current_user.role != 'admin'
      redirect_to root_path, :alert => show_alert(:permission_denied)
    end
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/index.html.haml
- title t('.title')

%p= t('.text')

%ul
  %li= link_to t('.links.statics'), statics_path

app/views/administration/statics.html.haml
- title t('.title')

%p= t('.text')

%ul
  %li
    = t('.events_amount')
    = @events_count
  %li
    = t('.matters_amount')
    = @matters_count
  %li
    = t('.careers_amount')
    = @careers_count
  %li
    = t('.plans_amount')
    = @plans_count
  %li
    = t('.equipment_amount')
    = @equipment_count
  %li
    = t('.spaces_amount')
    = @spaces_count
  %li
    = t('.events_expired')
    = @expired_events
  %li
    = t('.matters_assigned_to_events')
    = @assigned_matters
  %li
    = t('.free_events_amount')
    = @free_events
  %li
    = t('.spaces_assigned_to_events')
    = @assigned_spaces
  %li
    = t('.spaces_unassigned')
    = @unassigned_spaces
  %li
    = t('.matters_unassigned')
    = @unassigned_matters
  %li
    = t('.calendars_amount')
    = @calendars_count
  %li
    = t('.user_count')
    = @user_count
  %li
    = t('.admin_count')
    = @admin_count
  %li
    = t('.op_count')
    = @op_count
  %li
    = t('.normal_users_count')
    = @normal_users_count