config/routes.rb
DistroaulasRails3::Application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users do
    get 'reset_pass'
    put 'update_pass'
  end

  match '/administration' => 'administration#index', :as => 'administration_index'
  scope '/administration' do
    get '/statics' => 'administration#statics', :as => 'statics'
  end

  scope '/importer' do
    get '/' => 'importer#index', :as => 'importer_index'
    get '/space_types' => 'importer#space_types', :as => 'import_space_types'
    get '/spaces' => 'importer#spaces', :as => 'import_spaces'
    get '/plans' => 'importer#plans', :as => 'import_plans'
    get '/careers' => 'importer#careers', :as => 'import_careers'
    get '/matters' => 'importer#matters', :as => 'import_matters'

    get 'career_template' => 'importer#career_template', :as => 'career_template'
    get 'matter_template' => 'importer#matter_template', :as => 'matter_template'
    get 'space_template' => 'importer#space_template', :as => 'space_template'
    get 'space_type_template' => 'importer#space_type_template', :as => 'space_type_template'
    get 'plan_template' => 'importer#plan_template', :as => 'plan_template'

    get '/importer/result' => 'importer#result', :as => 'import_result'

    post '/space_types' => 'importer#upload_space_types', :as => 'importer_upload_space_types'
    post '/spaces' => 'importer#upload_spaces', :as => 'importer_upload_spaces'
    post '/plans' => 'importer#upload_plans', :as => 'importer_upload_plans'
    post '/careers' => 'importer#upload_careers', :as => 'importer_upload_careers'
    post '/matters' => 'importer#upload_matters', :as => 'importer_upload_matters'
  end

  scope '/equipment' do
    post '/search_events' => 'equipment#search_events', :as => 'search_events_equipment'
    get '/calendar' => 'equipment#calendar', :as => 'calendar_equipments'
    post '/calendar' => 'equipment#calendar', :as => 'calendar_equipments'
  end
  resources :equipment, :only => [:index, :new, :create, :update, :destroy, :edit] do
    member do
      get :assign_event
      post :assign_event
      post :create_events
      get :equipment_events
      delete :remove_event
      get :new_event
      post :create_single_event
    end
  end

  resources :calendars

  resources :events do
    collection do
      post 'calendar_preview'
      post 'generate_calendar'
      get 'generate_calendar'
    end
  end
  match 'ajax_get_responsibles_list' => 'events#get_responsibles_list'
  match 'ajax_search_events' => 'events#search'
  match 'ajax_careers_by_plan/:id' => 'careers#ajax_careers_by_plan'
  match 'new_event' => 'application#new_event', :as => 'new_event_from_free_space'
  match 'events/tip_summary/:id' => 'events#tip_summary'
  match '/ajax_event_info' => 'equipment#event_info'

  resources :space_types, :only => [:index, :new, :create, :update, :destroy, :edit]

  resources :plans

  resources :matters
  match 'ajax_get_matters_by_career/:id' => 'matters#ajax_get_matters_by_career'

  resources :spaces
  match 'ajax_free_spaces' => 'spaces#ajax_free_spaces'

  resources :careers

  root :to => "application#index"

  match '/statics/index' => "statics#index"
  match '/statics/:category/:doc' => 'statics#view_doc'

end

app/controllers/importer_controller.rb
class ImporterController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def space_types
  end

  def spaces
  end

  def plans
  end

  def careers
  end

  def matters
  end

  def career_template
    Career.generate_import_template.serialize(Rails.root.join('tmp', "#{Career.model_name.human}.xlsx"))
    send_file Rails.root.join('tmp', "#{Career.model_name.human}.xlsx")
  end

  def matter_template
    Matter.generate_import_template.serialize(Rails.root.join('tmp', "#{Matter.model_name.human}.xlsx"))
    send_file Rails.root.join('tmp', "#{Matter.model_name.human}.xlsx")
  end

  def space_template
    Space.generate_import_template.serialize(Rails.root.join('tmp', "#{Space.model_name.human}.xlsx"))
    send_file Rails.root.join('tmp', "#{Space.model_name.human}.xlsx")
  end

  def space_type_template
    SpaceType.generate_import_template.serialize(Rails.root.join('tmp', "#{SpaceType.model_name.human}.xlsx"))
    send_file Rails.root.join('tmp', "#{SpaceType.model_name.human}.xlsx")
  end

  def plan_template
    Plan.generate_import_template.serialize(Rails.root.join('tmp', "#{Plan.model_name.human}.xlsx"))
    send_file Rails.root.join('tmp', "#{Plan.model_name.human}.xlsx")
  end

  def upload_space_types
    flash[:notice] = show_notice :upload_space_types_success
    @import_results = SpaceType.import_xls params[:space_types][:file]
    render 'result'
  end

  def upload_spaces
    flash[:notice] = show_notice :upload_spaces_success
    @import_results = Space.import_xls params[:spaces][:file]
    render 'result'
  end

  def upload_plans
    flash[:notice] = show_notice :upload_plans_success
    @import_results = Plan.import_xls params[:plans][:file]
    render 'result'
  end

  def upload_careers
    flash[:notice] = show_notice :upload_careers_success
    @import_results = Career.import_xls params[:careers][:file]
    render 'result'
  end

  def upload_matters
    flash[:notice] = show_notice :upload_matters_success
    @import_results = Matter.import_xls params[:matters][:file]
    render 'result'
  end

  def result

  end


end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/views/importer/careers.html.haml
- title t('.title')

%p= t('.text')
%p= t('.text2')
%p= t('.text3')
%p= t('.text4')

%p
  = link_to t('.links.download_template'), career_template_path, :target => 'blank'

= semantic_form_for :careers, :url => importer_upload_careers_path, :html => {:multipart => true} do |f|
  = f.inputs do
    = f.input :file, :label => t('.labels.file'), :as => :file, :required => true
  = f.buttons do
    = f.commit_button t('.upload')

app/views/importer/index.html.haml
- title t('.title')

%p= t('.text')
%p= t('.text2')
%p= t('.text3')
%p= t('.text4')
%p= t('.text5')

%p
  %strong= t('.import')
  %ul
    %li= link_to SpaceType.model_name.human, import_space_types_path
    %li= link_to Space.model_name.human, import_spaces_path
    %li= link_to Plan.model_name.human, import_plans_path
    %li= link_to Career.model_name.human, import_careers_path
    %li= link_to Matter.model_name.human, import_matters_path

app/views/importer/matters.html.haml
- title t('.title')

%p= t('.text')
%p= t('.text2')
%p= t('.text3')
%p= t('.text4')

%p
  = link_to t('.links.download_template'), matter_template_path, :target => 'blank'

= semantic_form_for :matters, :url => importer_upload_matters_path, :html => {:multipart => true} do |f|
  = f.inputs do
    = f.input :file, :label => t('.labels.file'), :as => :file, :required => true
  = f.buttons do
    = f.commit_button t('.upload')

app/views/importer/plans.html.haml
- title t('.title')

%p= t('.text')
%p= t('.text2')
%p= t('.text3')
%p= t('.text4')

%p
  = link_to t('.links.download_template'), plan_template_path, :target => 'blank'

= semantic_form_for :plans, :url => importer_upload_plans_path, :html => {:multipart => true} do |f|
  = f.inputs do
    = f.input :file, :label => t('.labels.file'), :as => :file, :required => true
  = f.buttons do
    = f.commit_button t('.upload')

app/views/importer/result.html.haml
- title t('.title')

%p= t('.text')

%ul
  - @import_results.each do |line|
    %li= line

app/views/importer/space_types.html.haml
- title t('.title')

%p= t('.text')
%p= t('.text2')
%p= t('.text3')
%p= t('.text4')


%p
  = link_to t('.links.download_template'), space_type_template_path, :target => 'blank'

= semantic_form_for :space_types, :url => importer_upload_space_types_path, :html => {:multipart => true} do |f|
  = f.inputs do
    = f.input :file, :label => t('.labels.file'), :as => :file, :required => true
  = f.buttons do
    = f.commit_button t('.upload')

app/views/importer/spaces.html.haml
- title t('.title')

%p= t('.text')
%p= t('.text2')
%p= t('.text3')
%p= t('.text4')

%p
  = link_to t('.links.download_template'), space_template_path, :target => 'blank'

= semantic_form_for :spaces, :url => importer_upload_spaces_path, :html => {:multipart => true} do |f|
  = f.inputs do
    = f.input :file, :label => t('.labels.file'), :as => :file, :required => true
  = f.buttons do
    = f.commit_button t('.upload')