config/routes.rb
DistroaulasRails3::Application.routes.draw do
  devise_for :users, :path_prefix => 'd'
  resources :users do
    get 'reset_pass'
    put 'update_pass'
  end

  match '/administration' => 'administration#index', :as => 'administration_index'
  scope '/administration' do
    get '/statics' => 'administration#statics', :as => 'statics'
  end

  scope '/importer' do
    get '/' => 'importer#index', :as => 'importer_index'
    get '/space_types' => 'importer#space_types', :as => 'import_space_types'
    get '/spaces' => 'importer#spaces', :as => 'import_spaces'
    get '/plans' => 'importer#plans', :as => 'import_plans'
    get '/careers' => 'importer#careers', :as => 'import_careers'
    get '/matters' => 'importer#matters', :as => 'import_matters'

    get 'career_template' => 'importer#career_template', :as => 'career_template'
    get 'matter_template' => 'importer#matter_template', :as => 'matter_template'
    get 'space_template' => 'importer#space_template', :as => 'space_template'
    get 'space_type_template' => 'importer#space_type_template', :as => 'space_type_template'
    get 'plan_template' => 'importer#plan_template', :as => 'plan_template'

    get '/importer/result' => 'importer#result', :as => 'import_result'

    post '/space_types' => 'importer#upload_space_types', :as => 'importer_upload_space_types'
    post '/spaces' => 'importer#upload_spaces', :as => 'importer_upload_spaces'
    post '/plans' => 'importer#upload_plans', :as => 'importer_upload_plans'
    post '/careers' => 'importer#upload_careers', :as => 'importer_upload_careers'
    post '/matters' => 'importer#upload_matters', :as => 'importer_upload_matters'
  end

  scope '/equipment' do
    post '/search_events' => 'equipment#search_events', :as => 'search_events_equipment'
    get '/calendar' => 'equipment#calendar', :as => 'calendar_equipments'
    post '/calendar' => 'equipment#calendar', :as => 'calendar_equipments'
  end
  resources :equipment, :only => [:index, :new, :create, :update, :destroy, :edit] do
    member do
      get :assign_event
      post :assign_event
      post :create_events
      get :equipment_events
      delete :remove_event
      get :new_event
      post :create_single_event
    end
  end

  resources :calendars

  resources :events do
    collection do
      post 'calendar_preview'
      post 'generate_calendar'
      get 'generate_calendar'
    end
  end
  match 'ajax_get_responsibles_list' => 'events#get_responsibles_list'
  match 'ajax_search_events' => 'events#search'
  match 'ajax_careers_by_plan/:id' => 'careers#ajax_careers_by_plan'
  match 'new_event' => 'application#new_event', :as => 'new_event_from_free_space'
  match 'events/tip_summary/:id' => 'events#tip_summary'
  match '/ajax_event_info' => 'equipment#event_info'

  resources :space_types, :only => [:index, :new, :create, :update, :destroy, :edit]

  resources :plans

  resources :matters
  match 'ajax_get_matters_by_career/:id' => 'matters#ajax_get_matters_by_career'

  resources :spaces
  match 'ajax_free_spaces' => 'spaces#ajax_free_spaces'

  resources :careers

  root :to => "application#index"

  match '/statics/index' => "statics#index"
  match '/statics/:category/:doc' => 'statics#view_doc'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  attr_accessible :name, :careers, :career_ids

  has_many :careers

  validates :name, :presence => true

  def self.to_xlsx
    records = self.all
    xlsx = Axlsx::Package.new

    xlsx.workbook do |wb|
      styles = wb.styles

      header = styles.add_style(:border => Axlsx::STYLE_THIN_BORDER, :bg_color => '4b7399', :fg_color => 'FF', :b => true, :alignment => {:horizontal => :center})
      normal = styles.add_style(:border => Axlsx::STYLE_THIN_BORDER)

      wb.add_worksheet(:name => self.model_name.human) do |sheet|
        sheet.add_row [self.human_attribute_name(:name)], :style => header, :widths => [30]
        records.each do |record|
          sheet.add_row [record.name], :style => normal
        end

      end
    end
    return xlsx
  end

  def self.generate_import_template
    xlsx = Axlsx::Package.new

    xlsx.workbook do |wb|
      styles = wb.styles

      header = styles.add_style(:border => Axlsx::STYLE_THIN_BORDER, :bg_color => '4b7399', :fg_color => 'FF', :b => true, :alignment => {:horizontal => :center})

      wb.add_worksheet(:name => self.model_name.human) do |sheet|
        sheet.add_row [self.human_attribute_name(:name) + ' (*)'], :style => header, :widths => [30]
      end
    end
    return xlsx
  end

  def self.import_xls file=nil

    result = []
    if file
      plans_file = Spreadsheet.open file.path
      plans = plans_file.worksheet Plan.model_name.human
      counters = {:all => -1, :saved => 0, :not_saved => 0}
      1.upto plans.row_count do |row_index|
        counters[:all] += 1
        name = plans.row(row_index)[0].to_s.strip
        unless name.blank?
          plan = Plan.find_by_name name

          unless plan
            plan = Plan.new :name => name
            if plan.save!
              result << I18n.t('activerecord.plan_import_info.saved', :name => name)
              counters[:saved] += 1
            else
              result << I18n.t('activerecord.plan_import_info.not_saved', :name => name)
              counters[:not_saved] += 1
            end
          else
            result << I18n.t('activerecord.plan_import_info.duplicated', :name => name)
            counters[:not_saved] += 1
          end
        end
      end
    end
    if result.empty?
      result << I18n.t('activerecord.plan_import_info.empty')
    end
    result << I18n.t('activerecord.plan_import_info.finished')
    result << I18n.t('activerecord.plan_import_info.count', :all => counters[:all], :saved => counters[:saved], :not_saved => counters[:not_saved])
    return result

  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @plans = Plan.paginate(:page => params[:page])
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(params[:plan])
    if @plan.save
      redirect_to @plan, :notice => show_notice(:create_success)
    else
      render :action => 'new'
    end
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update_attributes(params[:plan])
      redirect_to @plan, :notice  => show_notice(:update_success)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_url, :notice => show_notice(:destroy_success)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.haml
= semantic_form_for @plan do |f|
  = f.inputs
  = f.buttons do
    = f.commit_button t('.commit')

app/views/plans/_list.html.haml
%table.index
  %tr
    %th= Plan.human_attribute_name :name
    %th= t('shared.actions')
  - for plan in plans
    %tr
      %td= plan.name
      %td
        = link_to t('.links.show'), plan if can? :read, plan
        = link_to t('.links.edit'), edit_plan_path(plan) if can? :edit, plan
        = link_to t('.links.destroy'), plan, :confirm => t('shared.destroy_confirmation'), :method => :delete if can? :destroy, plan

app/views/plans/edit.html.haml
- title t('.title')

= render 'form'

%p
  = link_to t('.links.show'), @plan, :class => "ui-corner-all button" if can? :read, @plan
  = link_to t('.links.back'), plans_path, :class => "ui-corner-all button" if can? :read, Plan

app/views/plans/index.html.haml
- title t('.title')

= render :partial => 'list', :locals => {:plans => @plans}

= will_paginate @plans
%p= link_to t('.links.new'), new_plan_path, :class => "ui-corner-all button" if can? :create, Plan

app/views/plans/new.html.haml
- title t('.title')

= render 'form'

%p= link_to t('.links.back'), plans_path, :class => "ui-corner-all button" if can? :read, Plan

app/views/plans/show.html.haml
- title t('.title')

%ul
  %li
    %strong= Plan.human_attribute_name(:name) + ':'
    = @plan.name
  %li
    %strong= Plan.human_attribute_name(:careers) + ':'
    = @plan.careers.size

%hr

%p
  %strong= t('.careers_list')

= render :partial => 'careers/list', :locals => {:careers => @plan.careers}

%p
  = link_to t('.links.edit'), edit_plan_path(@plan), :class => "ui-corner-all button" if can? :edit, @plan
  = link_to t('.links.destroy'), @plan, :confirm => t('shared.destroy_confirmation'), :method => :delete, :class => "ui-corner-all button" if can? :destroy, @plan
  = link_to t('.links.back'), plans_path, :class => "ui-corner-all button" if can? :read, Plan